### ISSUE TITLE
Solution for flash target

### ISSUE THREAD

**Issue by sh-dave** [laxa88/WyKhaTest#1]
Hi laxa,

i tried you example on flash and got an 'all buffers have to be cleared' error. I was able to fix it by adding ```,0,0``` in ```Kha/Sources/kha/graphics4/Graphics2.hx```:
```haxe
class Graphics2 extends kha.graphics2.Graphics {
...
	override public function clear(color: Color = null): Void {
		g.clear(color == null ? Color.Black : color, 0, 0);
	}
...
}
```

Could you try if this helps as temporary fix on android-native as well?

I think the actual issue is that somewhere a rendertarget with stencil and/or depthbuffer is created (may not be your fault, but a wrong default parameter somewhere in kha/kore), and these buffers aren't cleared correctly.

Will try to do an android-native build at home too, just not sure i'll find the time for it today and if it runs on my crappy htc :sweat_smile:

**Comment by sh-dave** [comment]
Have it running on android, but i'm not exactly sure now what the actual issue is?

**Comment by laxa88** [comment]
Ah, sorry i didn't explain it clearly. The issue is that if you click the top-left button, the circle on the bottom should change colour. But in android-native target, the circle at the bottom becomes a black square instead. Does that happen for you?

**Comment by laxa88** [comment]
Robert pinpointed the issue; it's a hack for android. To quote robert: "look for that string in OpenGL.cpp"

    // if rendered to a texture, strange things happen if the backbuffer is not cleared

So if I comment this line, the game would run as expected for android-native:

    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);

**Comment by sh-dave** [comment]
Hm, there seems to be more strange things going on though, b/c there is no blue circle on flash at all. I see the 2 textured buttons on top, can click right one to show the green + red, and click the red one to  make them disappear. Clicking the left texture button does nothing at all. And i have the same issue on android as you.

Bit offtopic: you probably should add an if in your engine classes, b/c there is no surface input in flash (and probably other targets)
```haxe
if (Surface.get() != null) {
    Surface.get().notify(....);
}
```

**Comment by sh-dave** [comment]
And i'm not entirely sure why uncommenting the line as robert suggested would work, as clear() is called in the begin() call and effectivly clears it again right after.

**Comment by laxa88** [comment]
Yea that's some strange thing going on with the image drawing. Does commenting the line as robert suggested actually fix the flash target?

Also, thanks for the bugfix suggestion! :D

**Comment by sh-dave** [comment]
Nope it couldn't as flash doesn't use the Kore (C++) backend, but it's own. If i find the time, i'll try to figure out whats wrong in the next days.

**Comment by sh-dave** [comment]
seems to be fixed with this https://github.com/KTXSoftware/Kha/commit/3fca78239cac2d2598bf8e3c540971557ef70cfa
